name: deploy.ia

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Copiar arquivos para VPS
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        ARGS: "-avz"
        SOURCE: "./"
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        REMOTE_PORT: ${{secrets.REMOTE_PORT}}
        TARGET: ${{secrets.TARGET_PRODUCTION}}

    - name: Ajustar permissões
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
            sudo chown -R www-data:www-data ${{ secrets.TARGET_PRODUCTION }}

    - name: Pós-deploy (instalar dependências e restart)
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
            cd ${{ secrets.TARGET_PRODUCTION }}
            source venv/bin/activate && pip install -r requirements.txt
            sudo supervisorctl restart pacoca-ia:*
